In [1]:
# Question 1: Convolution Operations with Different Parameters
# Author: <Vaishnavi gopi>
# Student id : 700754518
# Course: CS5720 - Neural Networks and Deep Learning

import numpy as np
import tensorflow as tf

# Define 5x5 input matrix
input_matrix = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 4],
    [1, 0, 1, 2, 3],
    [4, 1, 0, 1, 2],
    [3, 4, 1, 0, 1]
], dtype=np.float32)

# Define 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=np.float32)

# Reshape input and kernel for TensorFlow
input_tensor = tf.constant(input_matrix.reshape(1, 5, 5, 1))
kernel_tensor = tf.constant(kernel.reshape(3, 3, 1, 1))

# Function to apply convolution
def apply_conv(stride, padding):
    result = tf.nn.conv2d(input=input_tensor, filters=kernel_tensor,
                          strides=[1, stride, stride, 1], padding=padding)
    return tf.squeeze(result).numpy()

# Run and print results
print("Stride=1, Padding='VALID':\n", apply_conv(1, 'VALID'))
print("Stride=1, Padding='SAME':\n", apply_conv(1, 'SAME'))
print("Stride=2, Padding='VALID':\n", apply_conv(2, 'VALID'))
print("Stride=2, Padding='SAME':\n", apply_conv(2, 'SAME'))


Stride=1, Padding='VALID':
 [[-4. -2. -2.]
 [ 2. -4. -6.]
 [ 6.  2. -4.]]
Stride=1, Padding='SAME':
 [[-3. -4.  0.  0.  3.]
 [-3. -4. -2. -2.  5.]
 [-2.  2. -4. -6.  6.]
 [-5.  6.  2. -4.  3.]
 [-5.  6.  4. -2.  1.]]
Stride=2, Padding='VALID':
 [[-4. -2.]
 [ 6. -4.]]
Stride=2, Padding='SAME':
 [[-3.  0.  3.]
 [-2. -4.  6.]
 [-5.  4.  1.]]
